package mocks

import "context"

type Greeter interface {
	Greet() string
	PersonalGreet(name string) (string, error)
	AllTheGreets(who ...string) ([]string, error)
	GreetWithContext(ctx context.Context) string
}

type Convoluted interface {
	Convolute(Greeter, string, int, map[string]string) (map[string]string, error)
}

type SomeBirb interface {
	Dive(context.Context, SomeBirb) error
	Talk() string
}

type SomeBirbImpl struct {
	DaMap map[string]SomeBirb
}

func (b *SomeBirbImpl) Dive(ctx context.Context, sb SomeBirb) (err error) {
	return
}

type Owl struct {
	SomeBirbImpl
}

func (o *Owl) Talk() string {
	return "hoot!"
}

type Falcon struct {
	SomeBirbImpl
}

func (f *Falcon) Talk() string {
	return "screech!"
}

// DeepCopyInto is an autogenerated deepcopy function usually done by kubebuilder
func (in *Owl) DeepCopyInto(out *Owl) {
	*out = *in
	// this is for reference only.. a real DeepCopyInto would copy all the things (see k8s.io code for examples)
}

// DeepCopyInto is an autogenerated deepcopy function, usually done by kubebuilder
func (in *Falcon) DeepCopyInto(out *Falcon) {
	*out = *in
	// this is for reference only.. a real DeepCopyInto would copy all the things (see k8s.io code for examples)
}
