// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: birb
// template functions: https://github.com/vektra/mockery/blob/v3/template

package mocks

import (
	"reflect"

	"github.com/switch/birb"
	"github.com/switch/birb/handlers"
	"github.com/switch/birb/types"
)

func NewMockTestingT(t types.TestingT) *MockTestingT {
	t.Helper()
	tp := reflect.TypeOf(new(types.TestingT)).Elem()
	handler := handlers.NewHandler(t, tp)
	methodsMap := make(map[string]reflect.Method)
	for i := 0; i < tp.NumMethod(); i++ {
		method := tp.Method(i)
		methodsMap[method.Name] = method
	}
	mockVar := &MockTestingT{
		_handler:    handler,
		_methodsMap: methodsMap,
	}

	return mockVar
}

// MockTestingT is an autogenerated mock type for the TestingT type
type MockTestingT struct {
	_handler    *handlers.Handler
	_methodsMap map[string]reflect.Method
}

func (mock *MockTestingT) BirbHandler() *handlers.Handler {
	return mock._handler
}

// START Cleanup methods

// MOCK_Cleanup is the mock stubber for the Cleanup method of the MockTestingT type
func (mock *MockTestingT) MOCK_Cleanup(fn any) *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Cleanup"]
	args := []reflect.Value{
		reflect.ValueOf(fn),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// MOCKany_Cleanup is the mock stubber for the Cleanup method of the MockTestingT type
func (mock *MockTestingT) MOCKany_Cleanup() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Cleanup"]
	args := []reflect.Value{
		reflect.ValueOf(birb.WithAnyArgs()),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// Cleanup provides a mock function for the type MockTestingT
func (mock *MockTestingT) Cleanup(fn func()) {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Cleanup"]
	args := []any{
		fn,
	}
	// END method args extraction
	_ = mock._handler.Handle(methodType, args)
}

// CALLED_Cleanup is the mock verifier for the Cleanup method of the MockTestingT type
func (mock *MockTestingT) CALLED_Cleanup(givenArgs ...any) {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Cleanup"]
	args := []reflect.Value{}
	for _, a := range givenArgs {
		args = append(args, reflect.ValueOf(a))
	}
	// END method args extraction

	mock._handler.Verify(methodType, args)
}

// END Cleanup methods

// START Fatalf methods

// MOCK_Fatalf is the mock stubber for the Fatalf method of the MockTestingT type
func (mock *MockTestingT) MOCK_Fatalf(format any, args ...any) *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Fatalf"]
	args1 := []reflect.Value{
		reflect.ValueOf(format),
		reflect.ValueOf(args),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args1)
}

// MOCKany_Fatalf is the mock stubber for the Fatalf method of the MockTestingT type
func (mock *MockTestingT) MOCKany_Fatalf() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Fatalf"]
	args1 := []reflect.Value{
		reflect.ValueOf(birb.WithAnyArgs()),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args1)
}

// Fatalf provides a mock function for the type MockTestingT
func (mock *MockTestingT) Fatalf(format string, args ...any) {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Fatalf"]
	args1 := []any{
		format,
		args,
	}
	// END method args extraction
	_ = mock._handler.Handle(methodType, args1)
}

// CALLED_Fatalf is the mock verifier for the Fatalf method of the MockTestingT type
func (mock *MockTestingT) CALLED_Fatalf(givenArgs ...any) {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Fatalf"]
	args1 := []reflect.Value{}
	for _, a := range givenArgs {
		args1 = append(args1, reflect.ValueOf(a))
	}
	// END method args extraction

	mock._handler.Verify(methodType, args1)
}

// END Fatalf methods

// START Helper methods

// MOCK_Helper is the mock stubber for the Helper method of the MockTestingT type
func (mock *MockTestingT) MOCK_Helper() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Helper"]
	args := []reflect.Value{}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// Helper provides a mock function for the type MockTestingT
func (mock *MockTestingT) Helper() {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Helper"]
	args := []any{}
	// END method args extraction
	_ = mock._handler.Handle(methodType, args)
}

// CALLED_Helper is the mock verifier for the Helper method of the MockTestingT type
func (mock *MockTestingT) CALLED_Helper() {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Helper"]
	args := []reflect.Value{}
	// END method args extraction

	mock._handler.Verify(methodType, args)
}

// END Helper methods
