// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: birb
// template functions: https://github.com/vektra/mockery/blob/v3/template

package mocks

import (
	"reflect"

	"github.com/switch/birb"
	"github.com/switch/birb/handlers"
	"github.com/switch/birb/types"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/tools/record"
)

func NewMockEventRecorder(t types.TestingT) *MockEventRecorder {
	t.Helper()
	tp := reflect.TypeOf(new(record.EventRecorder)).Elem()
	handler := handlers.NewHandler(t, tp)
	methodsMap := make(map[string]reflect.Method)
	for i := 0; i < tp.NumMethod(); i++ {
		method := tp.Method(i)
		methodsMap[method.Name] = method
	}
	mockVar := &MockEventRecorder{
		_handler:    handler,
		_methodsMap: methodsMap,
	}

	return mockVar
}

// MockEventRecorder is an autogenerated mock type for the EventRecorder type
type MockEventRecorder struct {
	_handler    *handlers.Handler
	_methodsMap map[string]reflect.Method
}

func (mock *MockEventRecorder) BirbHandler() *handlers.Handler {
	return mock._handler
}

// START AnnotatedEventf methods

// MOCK_AnnotatedEventf is the mock stubber for the AnnotatedEventf method of the MockEventRecorder type
func (mock *MockEventRecorder) MOCK_AnnotatedEventf(object any, annotations any, eventtype any, reason any, messageFmt any, args ...any) *handlers.BirbMocker {
	// START method args extraction
	methodType := mock._methodsMap["AnnotatedEventf"]
	args1 := []reflect.Value{
		reflect.ValueOf(object),
		reflect.ValueOf(annotations),
		reflect.ValueOf(eventtype),
		reflect.ValueOf(reason),
		reflect.ValueOf(messageFmt),
		reflect.ValueOf(args),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args1)
}

// MOCKany_AnnotatedEventf is the mock stubber for the AnnotatedEventf method of the MockEventRecorder type
func (mock *MockEventRecorder) MOCKany_AnnotatedEventf() *handlers.BirbMocker {
	// START method args extraction
	methodType := mock._methodsMap["AnnotatedEventf"]
	args1 := []reflect.Value{
		reflect.ValueOf(birb.WithAnyArgs()),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args1)
}

// AnnotatedEventf provides a mock function for the type MockEventRecorder
func (mock *MockEventRecorder) AnnotatedEventf(object runtime.Object, annotations map[string]string, eventtype string, reason string, messageFmt string, args ...interface{}) {
	// START method args extraction
	methodType := mock._methodsMap["AnnotatedEventf"]
	args1 := []any{
		object,
		annotations,
		eventtype,
		reason,
		messageFmt,
		args,
	}
	// END method args extraction
	_ = mock._handler.Handle(methodType, args1)
}

// CALLED_AnnotatedEventf is the mock verifier for the AnnotatedEventf method of the MockEventRecorder type
func (mock *MockEventRecorder) CALLED_AnnotatedEventf(givenArgs ...any) {
	// START method args extraction
	methodType := mock._methodsMap["AnnotatedEventf"]
	args1 := []reflect.Value{}
	for _, a := range givenArgs {
		args1 = append(args1, reflect.ValueOf(a))
	}
	// END method args extraction

	mock._handler.Verify(methodType, args1)
}

// END AnnotatedEventf methods

// START Event methods

// MOCK_Event is the mock stubber for the Event method of the MockEventRecorder type
func (mock *MockEventRecorder) MOCK_Event(object any, eventtype any, reason any, message any) *handlers.BirbMocker {
	// START method args extraction
	methodType := mock._methodsMap["Event"]
	args := []reflect.Value{
		reflect.ValueOf(object),
		reflect.ValueOf(eventtype),
		reflect.ValueOf(reason),
		reflect.ValueOf(message),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// MOCKany_Event is the mock stubber for the Event method of the MockEventRecorder type
func (mock *MockEventRecorder) MOCKany_Event() *handlers.BirbMocker {
	// START method args extraction
	methodType := mock._methodsMap["Event"]
	args := []reflect.Value{
		reflect.ValueOf(birb.WithAnyArgs()),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// Event provides a mock function for the type MockEventRecorder
func (mock *MockEventRecorder) Event(object runtime.Object, eventtype string, reason string, message string) {
	// START method args extraction
	methodType := mock._methodsMap["Event"]
	args := []any{
		object,
		eventtype,
		reason,
		message,
	}
	// END method args extraction
	_ = mock._handler.Handle(methodType, args)
}

// CALLED_Event is the mock verifier for the Event method of the MockEventRecorder type
func (mock *MockEventRecorder) CALLED_Event(givenArgs ...any) {
	// START method args extraction
	methodType := mock._methodsMap["Event"]
	args := []reflect.Value{}
	for _, a := range givenArgs {
		args = append(args, reflect.ValueOf(a))
	}
	// END method args extraction

	mock._handler.Verify(methodType, args)
}

// END Event methods

// START Eventf methods

// MOCK_Eventf is the mock stubber for the Eventf method of the MockEventRecorder type
func (mock *MockEventRecorder) MOCK_Eventf(object any, eventtype any, reason any, messageFmt any, args ...any) *handlers.BirbMocker {
	// START method args extraction
	methodType := mock._methodsMap["Eventf"]
	args1 := []reflect.Value{
		reflect.ValueOf(object),
		reflect.ValueOf(eventtype),
		reflect.ValueOf(reason),
		reflect.ValueOf(messageFmt),
		reflect.ValueOf(args),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args1)
}

// MOCKany_Eventf is the mock stubber for the Eventf method of the MockEventRecorder type
func (mock *MockEventRecorder) MOCKany_Eventf() *handlers.BirbMocker {
	// START method args extraction
	methodType := mock._methodsMap["Eventf"]
	args1 := []reflect.Value{
		reflect.ValueOf(birb.WithAnyArgs()),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args1)
}

// Eventf provides a mock function for the type MockEventRecorder
func (mock *MockEventRecorder) Eventf(object runtime.Object, eventtype string, reason string, messageFmt string, args ...interface{}) {
	// START method args extraction
	methodType := mock._methodsMap["Eventf"]
	args1 := []any{
		object,
		eventtype,
		reason,
		messageFmt,
		args,
	}
	// END method args extraction
	_ = mock._handler.Handle(methodType, args1)
}

// CALLED_Eventf is the mock verifier for the Eventf method of the MockEventRecorder type
func (mock *MockEventRecorder) CALLED_Eventf(givenArgs ...any) {
	// START method args extraction
	methodType := mock._methodsMap["Eventf"]
	args1 := []reflect.Value{}
	for _, a := range givenArgs {
		args1 = append(args1, reflect.ValueOf(a))
	}
	// END method args extraction

	mock._handler.Verify(methodType, args1)
}

// END Eventf methods
