// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: birb
// template functions: https://github.com/vektra/mockery/blob/v3/template

package mocks

import (
	"context"
	"reflect"

	"github.com/switch/birb"
	"github.com/switch/birb/handlers"
	"github.com/switch/birb/types"
)

func NewMockGreeter(t types.TestingT) *MockGreeter {
	t.Helper()
	tp := reflect.TypeOf(new(Greeter)).Elem()
	handler := handlers.NewHandler(t, tp)
	methodsMap := make(map[string]reflect.Method)
	for i := 0; i < tp.NumMethod(); i++ {
		method := tp.Method(i)
		methodsMap[method.Name] = method
	}
	mockVar := &MockGreeter{
		_handler:    handler,
		_methodsMap: methodsMap,
	}

	return mockVar
}

// MockGreeter is an autogenerated mock type for the Greeter type
type MockGreeter struct {
	_handler    *handlers.Handler
	_methodsMap map[string]reflect.Method
}

func (mock *MockGreeter) BirbHandler() *handlers.Handler {
	return mock._handler
}

// START AllTheGreets methods

// MOCK_AllTheGreets is the mock stubber for the AllTheGreets method of the MockGreeter type
func (mock *MockGreeter) MOCK_AllTheGreets(who ...any) *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["AllTheGreets"]
	args := []reflect.Value{
		reflect.ValueOf(who),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// MOCKfallback_AllTheGreets is the fallback stubber for the AllTheGreets method.
// Fallback stubs have the lowest priority and are only used when all other stubs are exhausted.
// They are excluded from VerifyAllMatchersCalled() checks.
func (mock *MockGreeter) MOCKfallback_AllTheGreets() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["AllTheGreets"]
	args := []reflect.Value{}
	// END method args extraction

	return mock._handler.MockFallback(methodType, args)
}

// AllTheGreets provides a mock function for the type MockGreeter
func (mock *MockGreeter) AllTheGreets(who ...string) ([]string, error) {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["AllTheGreets"]
	args := []any{
		who,
	}
	// END method args extraction
	outs := mock._handler.Handle(methodType, args)
	if len(outs) != 2 {
		mock._handler.TestingT().Fatalf(
			"Expected %d outputs, got %d\nThis usually happens because of a ThenReturn mismatch",
			2,
			len(outs),
		)
	}
	r0, _ := outs[0].([]string)
	r1, _ := outs[1].(error)

	return r0, r1
}

// CALLED_AllTheGreets is the mock verifier for the AllTheGreets method of the MockGreeter type
func (mock *MockGreeter) CALLED_AllTheGreets(givenArgs ...any) {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["AllTheGreets"]
	args := []reflect.Value{}
	for _, a := range givenArgs {
		args = append(args, reflect.ValueOf(a))
	}
	// END method args extraction

	mock._handler.Verify(methodType, args)
}

// END AllTheGreets methods

// START Greet methods

// MOCK_Greet is the mock stubber for the Greet method of the MockGreeter type
func (mock *MockGreeter) MOCK_Greet() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Greet"]
	args := []reflect.Value{}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// MOCKfallback_Greet is the fallback stubber for the Greet method.
// Fallback stubs have the lowest priority and are only used when all other stubs are exhausted.
// They are excluded from VerifyAllMatchersCalled() checks.
func (mock *MockGreeter) MOCKfallback_Greet() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Greet"]
	args := []reflect.Value{}
	// END method args extraction

	return mock._handler.MockFallback(methodType, args)
}

// Greet provides a mock function for the type MockGreeter
func (mock *MockGreeter) Greet() string {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Greet"]
	args := []any{}
	// END method args extraction
	outs := mock._handler.Handle(methodType, args)
	if len(outs) != 1 {
		mock._handler.TestingT().Fatalf(
			"Expected %d outputs, got %d\nThis usually happens because of a ThenReturn mismatch",
			1,
			len(outs),
		)
	}
	r0, _ := outs[0].(string)

	return r0
}

// CALLED_Greet is the mock verifier for the Greet method of the MockGreeter type
func (mock *MockGreeter) CALLED_Greet() {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Greet"]
	args := []reflect.Value{}
	// END method args extraction

	mock._handler.Verify(methodType, args)
}

// END Greet methods

// START GreetWithContext methods

// MOCK_GreetWithContext is the mock stubber for the GreetWithContext method of the MockGreeter type
func (mock *MockGreeter) MOCK_GreetWithContext(ctx any) *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["GreetWithContext"]
	args := []reflect.Value{
		reflect.ValueOf(ctx),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// MOCKany_GreetWithContext is the mock stubber for the GreetWithContext method of the MockGreeter type
func (mock *MockGreeter) MOCKany_GreetWithContext() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["GreetWithContext"]
	args := []reflect.Value{
		reflect.ValueOf(birb.WithAnyArgs()),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// MOCKfallback_GreetWithContext is the fallback stubber for the GreetWithContext method.
// Fallback stubs have the lowest priority and are only used when all other stubs are exhausted.
// They are excluded from VerifyAllMatchersCalled() checks.
func (mock *MockGreeter) MOCKfallback_GreetWithContext() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["GreetWithContext"]
	args := []reflect.Value{
		reflect.ValueOf(birb.WithAnyArgs()),
	}
	// END method args extraction

	return mock._handler.MockFallback(methodType, args)
}

// GreetWithContext provides a mock function for the type MockGreeter
func (mock *MockGreeter) GreetWithContext(ctx context.Context) string {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["GreetWithContext"]
	args := []any{
		ctx,
	}
	// END method args extraction
	outs := mock._handler.Handle(methodType, args)
	if len(outs) != 1 {
		mock._handler.TestingT().Fatalf(
			"Expected %d outputs, got %d\nThis usually happens because of a ThenReturn mismatch",
			1,
			len(outs),
		)
	}
	r0, _ := outs[0].(string)

	return r0
}

// CALLED_GreetWithContext is the mock verifier for the GreetWithContext method of the MockGreeter type
func (mock *MockGreeter) CALLED_GreetWithContext(givenArgs ...any) {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["GreetWithContext"]
	args := []reflect.Value{}
	for _, a := range givenArgs {
		args = append(args, reflect.ValueOf(a))
	}
	// END method args extraction

	mock._handler.Verify(methodType, args)
}

// END GreetWithContext methods

// START PersonalGreet methods

// MOCK_PersonalGreet is the mock stubber for the PersonalGreet method of the MockGreeter type
func (mock *MockGreeter) MOCK_PersonalGreet(name any) *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["PersonalGreet"]
	args := []reflect.Value{
		reflect.ValueOf(name),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// MOCKany_PersonalGreet is the mock stubber for the PersonalGreet method of the MockGreeter type
func (mock *MockGreeter) MOCKany_PersonalGreet() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["PersonalGreet"]
	args := []reflect.Value{
		reflect.ValueOf(birb.WithAnyArgs()),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// MOCKfallback_PersonalGreet is the fallback stubber for the PersonalGreet method.
// Fallback stubs have the lowest priority and are only used when all other stubs are exhausted.
// They are excluded from VerifyAllMatchersCalled() checks.
func (mock *MockGreeter) MOCKfallback_PersonalGreet() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["PersonalGreet"]
	args := []reflect.Value{
		reflect.ValueOf(birb.WithAnyArgs()),
	}
	// END method args extraction

	return mock._handler.MockFallback(methodType, args)
}

// PersonalGreet provides a mock function for the type MockGreeter
func (mock *MockGreeter) PersonalGreet(name string) (string, error) {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["PersonalGreet"]
	args := []any{
		name,
	}
	// END method args extraction
	outs := mock._handler.Handle(methodType, args)
	if len(outs) != 2 {
		mock._handler.TestingT().Fatalf(
			"Expected %d outputs, got %d\nThis usually happens because of a ThenReturn mismatch",
			2,
			len(outs),
		)
	}
	r0, _ := outs[0].(string)
	r1, _ := outs[1].(error)

	return r0, r1
}

// CALLED_PersonalGreet is the mock verifier for the PersonalGreet method of the MockGreeter type
func (mock *MockGreeter) CALLED_PersonalGreet(givenArgs ...any) {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["PersonalGreet"]
	args := []reflect.Value{}
	for _, a := range givenArgs {
		args = append(args, reflect.ValueOf(a))
	}
	// END method args extraction

	mock._handler.Verify(methodType, args)
}

// END PersonalGreet methods

func NewMockConvoluted(t types.TestingT) *MockConvoluted {
	t.Helper()
	tp := reflect.TypeOf(new(Convoluted)).Elem()
	handler := handlers.NewHandler(t, tp)
	methodsMap := make(map[string]reflect.Method)
	for i := 0; i < tp.NumMethod(); i++ {
		method := tp.Method(i)
		methodsMap[method.Name] = method
	}
	mockVar := &MockConvoluted{
		_handler:    handler,
		_methodsMap: methodsMap,
	}

	return mockVar
}

// MockConvoluted is an autogenerated mock type for the Convoluted type
type MockConvoluted struct {
	_handler    *handlers.Handler
	_methodsMap map[string]reflect.Method
}

func (mock *MockConvoluted) BirbHandler() *handlers.Handler {
	return mock._handler
}

// START Convolute methods

// MOCK_Convolute is the mock stubber for the Convolute method of the MockConvoluted type
func (mock *MockConvoluted) MOCK_Convolute(greeter any, s any, n any, stringToString any) *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Convolute"]
	args := []reflect.Value{
		reflect.ValueOf(greeter),
		reflect.ValueOf(s),
		reflect.ValueOf(n),
		reflect.ValueOf(stringToString),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// MOCKany_Convolute is the mock stubber for the Convolute method of the MockConvoluted type
func (mock *MockConvoluted) MOCKany_Convolute() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Convolute"]
	args := []reflect.Value{
		reflect.ValueOf(birb.WithAnyArgs()),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// MOCKfallback_Convolute is the fallback stubber for the Convolute method.
// Fallback stubs have the lowest priority and are only used when all other stubs are exhausted.
// They are excluded from VerifyAllMatchersCalled() checks.
func (mock *MockConvoluted) MOCKfallback_Convolute() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Convolute"]
	args := []reflect.Value{
		reflect.ValueOf(birb.WithAnyArgs()),
	}
	// END method args extraction

	return mock._handler.MockFallback(methodType, args)
}

// Convolute provides a mock function for the type MockConvoluted
func (mock *MockConvoluted) Convolute(greeter Greeter, s string, n int, stringToString map[string]string) (map[string]string, error) {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Convolute"]
	args := []any{
		greeter,
		s,
		n,
		stringToString,
	}
	// END method args extraction
	outs := mock._handler.Handle(methodType, args)
	if len(outs) != 2 {
		mock._handler.TestingT().Fatalf(
			"Expected %d outputs, got %d\nThis usually happens because of a ThenReturn mismatch",
			2,
			len(outs),
		)
	}
	r0, _ := outs[0].(map[string]string)
	r1, _ := outs[1].(error)

	return r0, r1
}

// CALLED_Convolute is the mock verifier for the Convolute method of the MockConvoluted type
func (mock *MockConvoluted) CALLED_Convolute(givenArgs ...any) {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Convolute"]
	args := []reflect.Value{}
	for _, a := range givenArgs {
		args = append(args, reflect.ValueOf(a))
	}
	// END method args extraction

	mock._handler.Verify(methodType, args)
}

// END Convolute methods

func NewMockSomeBirb(t types.TestingT) *MockSomeBirb {
	t.Helper()
	tp := reflect.TypeOf(new(SomeBirb)).Elem()
	handler := handlers.NewHandler(t, tp)
	methodsMap := make(map[string]reflect.Method)
	for i := 0; i < tp.NumMethod(); i++ {
		method := tp.Method(i)
		methodsMap[method.Name] = method
	}
	mockVar := &MockSomeBirb{
		_handler:    handler,
		_methodsMap: methodsMap,
	}

	return mockVar
}

// MockSomeBirb is an autogenerated mock type for the SomeBirb type
type MockSomeBirb struct {
	_handler    *handlers.Handler
	_methodsMap map[string]reflect.Method
}

func (mock *MockSomeBirb) BirbHandler() *handlers.Handler {
	return mock._handler
}

// START Dive methods

// MOCK_Dive is the mock stubber for the Dive method of the MockSomeBirb type
func (mock *MockSomeBirb) MOCK_Dive(context1 any, someBirb any) *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Dive"]
	args := []reflect.Value{
		reflect.ValueOf(context1),
		reflect.ValueOf(someBirb),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// MOCKany_Dive is the mock stubber for the Dive method of the MockSomeBirb type
func (mock *MockSomeBirb) MOCKany_Dive() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Dive"]
	args := []reflect.Value{
		reflect.ValueOf(birb.WithAnyArgs()),
	}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// MOCKfallback_Dive is the fallback stubber for the Dive method.
// Fallback stubs have the lowest priority and are only used when all other stubs are exhausted.
// They are excluded from VerifyAllMatchersCalled() checks.
func (mock *MockSomeBirb) MOCKfallback_Dive() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Dive"]
	args := []reflect.Value{
		reflect.ValueOf(birb.WithAnyArgs()),
	}
	// END method args extraction

	return mock._handler.MockFallback(methodType, args)
}

// Dive provides a mock function for the type MockSomeBirb
func (mock *MockSomeBirb) Dive(context1 context.Context, someBirb SomeBirb) error {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Dive"]
	args := []any{
		context1,
		someBirb,
	}
	// END method args extraction
	outs := mock._handler.Handle(methodType, args)
	if len(outs) != 1 {
		mock._handler.TestingT().Fatalf(
			"Expected %d outputs, got %d\nThis usually happens because of a ThenReturn mismatch",
			1,
			len(outs),
		)
	}
	r0, _ := outs[0].(error)

	return r0
}

// CALLED_Dive is the mock verifier for the Dive method of the MockSomeBirb type
func (mock *MockSomeBirb) CALLED_Dive(givenArgs ...any) {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Dive"]
	args := []reflect.Value{}
	for _, a := range givenArgs {
		args = append(args, reflect.ValueOf(a))
	}
	// END method args extraction

	mock._handler.Verify(methodType, args)
}

// END Dive methods

// START Talk methods

// MOCK_Talk is the mock stubber for the Talk method of the MockSomeBirb type
func (mock *MockSomeBirb) MOCK_Talk() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Talk"]
	args := []reflect.Value{}
	// END method args extraction

	return mock._handler.Mock(methodType, args)
}

// MOCKfallback_Talk is the fallback stubber for the Talk method.
// Fallback stubs have the lowest priority and are only used when all other stubs are exhausted.
// They are excluded from VerifyAllMatchersCalled() checks.
func (mock *MockSomeBirb) MOCKfallback_Talk() *handlers.BirbMocker {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Talk"]
	args := []reflect.Value{}
	// END method args extraction

	return mock._handler.MockFallback(methodType, args)
}

// Talk provides a mock function for the type MockSomeBirb
func (mock *MockSomeBirb) Talk() string {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Talk"]
	args := []any{}
	// END method args extraction
	outs := mock._handler.Handle(methodType, args)
	if len(outs) != 1 {
		mock._handler.TestingT().Fatalf(
			"Expected %d outputs, got %d\nThis usually happens because of a ThenReturn mismatch",
			1,
			len(outs),
		)
	}
	r0, _ := outs[0].(string)

	return r0
}

// CALLED_Talk is the mock verifier for the Talk method of the MockSomeBirb type
func (mock *MockSomeBirb) CALLED_Talk() {
	mock._handler.TestingT().Helper()
	// START method args extraction
	methodType := mock._methodsMap["Talk"]
	args := []reflect.Value{}
	// END method args extraction

	mock._handler.Verify(methodType, args)
}

// END Talk methods
