//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package deepcopy

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NestedConfig) DeepCopyInto(out *NestedConfig) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NestedConfig.
func (in *NestedConfig) DeepCopy() *NestedConfig {
	if in == nil {
		return nil
	}
	out := new(NestedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestConfig) DeepCopyInto(out *TestConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.Nested != nil {
		in, out := &in.Nested, &out.Nested
		*out = new(NestedConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestConfig.
func (in *TestConfig) DeepCopy() *TestConfig {
	if in == nil {
		return nil
	}
	out := new(TestConfig)
	in.DeepCopyInto(out)
	return out
}
