#!/usr/bin/env bash
# birbTemplates.sh
# This throws the templates into the cmd/birb package.

# Usage: ./birbTemplates.sh

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TEMPLATES_DIR="$BASEDIR/../../templates"

TEMPLATE_DATA=$(base64 -i "$TEMPLATES_DIR/mockery.go.tmpl")
TEMPLATE_SCHEMA=$(base64 -i "$TEMPLATES_DIR/mockery.go.tmpl.schema.json")

cat <<EOF > "$BASEDIR/birbTemplates.go"
// Code generated by cmd/birb/birbTemplates.sh; DO NOT EDIT.
package main

const (
  MockeryTemplate = "$TEMPLATE_DATA"
  MockerySchema  = "$TEMPLATE_SCHEMA"
)
EOF
echo "Templates written to $BASEDIR/birbTemplates.go"
